steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/quantum-star-435523-g9/flask-app:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/quantum-star-435523-g9/flask-app:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/frontend-deployment', 'flask-app=gcr.io/quantum-star-435523-g9/flask-app:$SHORT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
images:
- 'vihangihk/flask-frontend:$SHORT_SHA'
substitutions:
  _ZONE: 'us-central1-a'
  _CLUSTER_NAME: 'terraform-gke'

options:
  logging: CLOUD_LOGGING_ONLY

