apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  replicas: 3 # Number of desired replicas
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend
          image: gcr.io/quantum-star-435523-g9/frontend-app-nginx:latest
          ports:
            - containerPort: 80
